all:

# Restore the pre-25.1 Emacs icon with the prettier traditional one
emacs-icon: $(wildcard .emacs.d/*.icns)
	@cp -f $^ /Applications/Emacs.app/Contents/Resources/
	@echo "Emacs icon updated. Restart system to force display in Finder/Spotlight.";


# Compile a cutting-edge build of V8
v8:
	@cd /Users/johngardner/Mirrors/v8;\
	git pull;\
	tools/dev/v8gen.py x64.release;\
	ninja -C out.gn/x64.release;\
	tools/run-tests.py --gn;\
	path=/usr/local/bin/v8;\
	[ -L $$path ] || ln -fs "$$path";\
	$$path --help


# Update lists of installed packages
lists: etc/install/package-lists.sh
	@ echo '# Auto-generated by `make lists`' > $^;
	$(call update-list,npm_modules,"ls /usr/local/lib/node_modules | sed -Ee '/npm|uglifyjs/d'")
	$(call update-list,ruby_gems,"gem list --no-versions | grep -v '* LOCAL GEMS *'")
	$(call update-list,pip_packages,"pip2 list --format=legacy | cut -d ' ' -f1")
	$(call update-list,cpan_modules,"etc/install/cpanlist.pl")
	cd etc/install && brew bundle dump --force;
update-list = \
	printf '\n%s"\n' "$(1)=" >> $^; \
	eval $(2) | sort -fi | sed -Ee 's/^/\t/g' >> $^; \
	printf '";\n' >> $^;
.PHONY: lists



# Reconnect hard-links after downloading an updated eBook
relink-ebooks:
	books=~/Downloads/exploring-es6.*; \
	dest=~/Documents/eBooks/Exploring\ ES6/; \
	for i in $$books; do [ ! -f "$$i" ] || mv $$i "$$dest" && \
		ln -f "$${dest}"$$(basename "$$i") ~/Dropbox/Backups/; \
	done;
	open /Applications/Dropbox.app
.PHONY: relink-ebooks


# Compress and backup iTunes library database
itunes := ~/Dropbox/Backups/itunes-backup.zip
$(itunes): ~/Music/iTunes
	@zip -r $@ $^/*.{itl,xml}; \
	open /Applications/Dropbox.app; \
	hdd="/Volumes/Amra Helion"; \
	[ ! -d "$$hdd" ] || cp "$@" "$$hdd/MacBook/";
itunes-backup: $(itunes)
