.Dd March 25, 2019
.Dt CHOCO-UPGRADE 1
.Os Windows
.
.Sh NAME
.Nm choco-upgrade ,
.Nm cup
.Nd upgrade packages from various sources
.
.Sh SYNOPSIS
.Nm choco Cm upgrade
.	Op pkg Ns | Ns all
.	Op pkg2 pkgN
.	Op options
.Nm cup
.	Op pkg Ns | Ns all
.	Op pkg2 pkgN
.	Op options
.
.Sh DESCRIPTION
Upgrades a package or a list of packages.
Some may prefer to use
.Sy cup
as a shortcut for
.Ql choco upgrade .
If you do not have a package installed,
.Sy upgrade
will install it.
.
.Pp
100% compatible with older Chocolatey client (0.9.8.x and below) with options and switches.
Add
.Fl y
for previous behaviour with no prompt.
In most cases you can still pass options and switches with one
.Pq Dq \N'45' .
For more details, see the command reference
.Pq Dq choco -?
or
.Dq man choco .
.
.Pp
.Sy NOTE :
.Ql all
is a special package keyword that will allow you to upgrade all currently installed packages.
.
.Pp
Skip upgrading certain packages with
.Ql choco pin
or with the option
.Fl -except .
.
.Pp
Chocolatey Pro / Business automatically synchronises with
.Dq Programs and Features ,
ensuring automatically updating apps' versions (like Chrome) are up to date in Chocolatey\(cqs repository.
.
.
.Ss Options
.Sy NOTE :
Options and switches apply to all items passed,
so if you are installing multiple packages, and you use
.Fl -version Ns No = Ns Ar 1.0.0 ,
it is going to look for and try to install version 1.0.0 of every package passed.
So please split out multiple package calls when wanting to pass specific options.
.
.Bl -tag -width 4n
.It Fl -allowdowngrade , Fl -allow-downgrade
Whether an attempt at downgrading should be allowed.
Defaults to false.
.
.It Fl -allowemptychecksum , Fl -allowemptychecksums , Fl -allow-empty-checksums
Whether to allow packages to have empty/missing checksums for downloaded resources from non-secure locations (HTTP, FTP).
Use of this switch is not recommended if using sources that download resources from the internet.
Overrides the default feature
.Dq allowEmptyChecksums
set to
.Ar False .
Available since v0.10.0.
.
.It Fl -allowemptychecksumsecure , Fl -allowemptychecksumssecure , Fl -allow-empty-checksums-secure
Whether to allow packages to have empty checksums for downloaded resources from secure locations (HTTPS).
Overrides the default feature
.Dq allowEmptyChecksumsSecure
set to
.Ar True .
Available since v0.10.0.
.
.It Fl -argsglobal , Fl -args-global , Fl -installargsglobal , Fl -install-args-global , \
Fl -applyargstodependencies , Fl -apply-args-to-dependencies , Fl -apply-install-arguments-to-dependencies
Whether install arguments should be applied to dependent packages.
Defaults to false.
.
.It Fl -cert , Fl Ns No = Ns Ar VALUE
Client certificate \(en
PFX pathname for an x509 authenticated feeds.
Defaults to empty.
Available since v0.9.10.
.
.It Fl -checksum , Fl -downloadchecksum , Fl -download-checksum Ns No = Ns Ar VALUE
A user-provided checksum for downloaded resources for the package.
Overrides the package checksum (if it has one).
Defaults to empty.
Available since v0.10.0.
.
.It Fl -checksum64 , Fl -checksumx64 , Fl -downloadchecksumx64 , Fl -download-checksum-x64 Ns No = Ns Ar VALUE
A user-provided checksum for 64-bit downloaded resources for the package.
Overrides the package 64-bit checksum (if it has one).
Defaults to same as Download Checksum.
Available since v0.10.0.
.
.It Fl -checksumtype , Fl -checksum-type , Fl -downloadchecksumtype , Fl -download-checksum-type Ns No = Ns Ar VALUE
A user-provided checksum type.
Overrides the package checksum type (if it has one).
Used in conjunction with Download Checksum.
Available values are
.Ql md5 ,
.Ql sha1 ,
.Ql sha256 ,
or
.Ql sha512 .
Defaults to
.Ql md5 .
Available since v0.10.0.
.
.It Fl -checksumtype64 , Fl -checksumtypex64 , Fl -checksum-type-x64 , Fl -downloadchecksumtypex64 , Fl -download-checksum-type-x64 Ns No = Ns Ar VALUE
A user-provided checksum for 64-bit downloaded resources for the package.
Overrides the package 64-bit checksum (if it has one).
Used in conjunction with Download Checksum 64-bit
Available values are
.Ql md5 ,
.Ql sha1 ,
.Ql sha256
or
.Ql sha512 .
Defaults to same as Download Checksum Type.
Available since v0.10.0.
.
.It Fl -cp , Fl -certpassword Ns No = Ns Ar VALUE
The client certificate's password to the source.
Defaults to empty.
Available since v0.9.10.
.
.It Fl -except Ns No = Ns Ar VALUE
A comma-separated list of package names that should not be upgraded when upgrading
.Sy all .
Defaults to the empty string.
Available since v0.9.10.
.
.It Fl -exclude-pre , Fl -exclude-prerelease , Fl -exclude-prereleases
Whether prereleases should be ignored for upgrades.
Will be ignored if you pass
.Fl -pre .
Available since v0.10.4.
.
.It Fl -failonnotinstalled , Fl -fail-on-not-installed
If a package is not already installed, fail instead of installing.
.
.It Fl -failonunfound , Fl -fail-on-unfound
If a package is not found in sources specified, fail instead of warn.
.
.It Fl i , Fl -ignoredependencies , Fl -ignore-dependencies
Ignore dependencies when upgrading package(s).
Defaults to false.
.
.It Fl -ia , Fl -installargs , Fl -installarguments , Fl -install-arguments Ns No = Ns Ar VALUE
Install Arguments to pass to the native installer in the package.
Defaults to unspecified.
.
.It Fl -ignore-unfound
Ignore packages that are not found on the sources used (or the defaults).
Overrides the default feature
.Dq ignoreUnfoundPackagesOnUpgradeOutdated
set to
.Ar False .
Available since v0.10.9.
.
.It Fl -ignorechecksum , Fl -ignore-checksum , Fl -ignorechecksums , Fl -ignore-checksums
Ignore checksums provided by the package.
Overrides the default feature
.Dq checksumFiles
set to
.Ar True .
Available since v0.9.9.9.
.
.It Fl -ignorepackagecodes , Fl -ignorepackageexitcodes , Fl -ignore-package-codes , Fl -ignore-package-exit-codes
Exit with a 0 for success and 1 for non-success, no matter what package scripts provide for exit codes.
Overrides the default feature
.Dq usePackageExitCodes
set to
.Ar True .
Available since v0.9.10.
.
.It Fl -ignorerememberedargs , Fl -ignorerememberedarguments , Fl -ignorerememberedoptions , \
Fl -ignore-remembered-args , Fl -ignore-remembered-arguments , Fl -ignore-remembered-options
Ignore the arguments and options used during install for upgrade.
Overrides the default feature
.Dq useRememberedArgumentsForUpgrades
set to
.Ar False .
Available since v0.10.4.
.
.It Fl m , Fl -sxs , Fl -sidebyside , Fl -side-by-side , Fl -allowmultiple , \
Fl -allow-multiple , Fl -allowmultipleversions , Fl -allow-multiple-versions
Whether multiple versions of a package should be installed.
Defaults to false.
.
.It Fl n , Fl -skippowershell , Fl -skip-powershell , Fl -skipscripts , Fl -skip-scripts , Fl -skip-automation-scripts
Do not run
.Pa chocolateyInstall.ps1 .
Defaults to false.
.
.It Fl -notsilent , Fl -not-silent
Do not install this silently.
Defaults to false.
.
.It Fl o , Fl -override , Fl -overrideargs , Fl -overridearguments , Fl -override-arguments
Whether install arguments should be used exclusively without appending to current package passed arguments.
Defaults to false.
.
.It Fl p , Fl -password Ns No = Ns Ar VALUE
User's password to the source.
Defaults to empty.
.
.It Fl -params , Fl -parameters , Fl -pkgparameters , Fl -packageparameters , Fl -package-parameters Ns No = Ns Ar VALUE
Parameters to pass to the package.
Defaults to unspecified.
.
.It Fl -paramsglobal , Fl -params-global , Fl -packageparametersglobal , Fl -package-parameters-global , \
Fl -applyparamstodependencies , Fl -apply-params-to-dependencies , Fl -apply-package-parameters-to-dependencies
Whether package parameters should be applied to dependent packages.
Defaults to false.
.
.It Fl -pre , Fl -prerelease
Whether to include prereleases.
Defaults to false.
.
.It Fl -requirechecksum , Fl -requirechecksums , Fl -require-checksums
Require packages to have checksums for downloaded resources (both non-secure and secure).
Overrides the default feature
.Dq allowEmptyChecksums
set to
.Ar False
and
.Dq allowEmptyChecksumsSecure
set to
.Ar True .
Available since v0.10.0.
.
.It Fl s , Fl -source Ns No = Ns Ar VALUE
The source to find the package(s) to install.
Special sources include:
.Ql ruby ,
.Ql webpi ,
.Ql cygwin ,
.Ql windowsfeatures ,
and
.Ql python .
To specify more than one source,
pass it with a semicolon separating the values (e.g.
.Pq Dq 'source1;source2' .
Defaults to default feeds.
.
.It Fl -stoponfirstfailure , Fl -stop-on-first-failure , Fl -stop-on-first-package-failure
Stop running install, upgrade or uninstall on first package failure instead of continuing with others.
Overrides the default feature
.Dq stopOnFirstPackageFailure
set to
.Ar False .
Available since v0.10.4.
.
.It Fl u , Fl -user Ns No = Ns Ar VALUE
Username, used with authenticated feeds.
Defaults to the empty string.
.
.It Fl -usepackagecodes , Fl -usepackageexitcodes , Fl -use-package-codes , Fl -use-package-exit-codes
Package scripts can provide exit codes.
Use those for
.Nm choco Ns \(cqs exit code when non-zero
(this value can come from a dependency package).
Chocolatey defines valid exit codes as 0, 1605, 1614, 1641, 3010.
Overrides the default feature
.Dq usePackageExitCodes
set to
.Ar True .
Available since v0.9.10.
.
.It Fl -userememberedargs , -userememberedarguments , Fl -userememberedoptions , \
Fl -use-remembered-args , Fl -use-remembered-arguments , Fl -use-remembered-options
Use the arguments and options used during install for upgrade.
Does not override arguments being passed at runtime.
Overrides the default feature
.Dq useRememberedArgumentsForUpgrades
set to
.Ar False .
Available since v0.10.4.
.
.It Fl -version Ns No = Ns Ar VALUE
A specific version to install.
Defaults to unspecified.
.
.It Fl -x86 , Fl -forcex86
Force x86 (32b-it) installation on 64-bit systems.
Defaults to false.
.El
.
.Sh EXAMPLES
.Bd -literal
.Nm choco Cm upgrade No chocolatey
.Nm choco Cm upgrade No notepadplusplus googlechrome atom 7zip
.Nm choco Cm upgrade No notepadplusplus googlechrome atom 7zip Fl dvfy
.Nm choco Cm upgrade No git Fl -params Ns No = Ns Qo Ar '/GitAndUnixToolsOnPath /NoAutoCrlf' Qc Fl y
.Nm choco Cm upgrade No nodejs.install Fl -version Ar 0.10.35
.Nm choco Cm upgrade No git -s Qq 'https://somewhere/out/there'
.Nm choco Cm upgrade No git -s Qo 'https://somewhere/protected' Qc Fl u Ar user Fl p Ar pass
.Nm choco Cm upgrade No all
.Nm choco Cm upgrade No all Fl -except Ns No = Ns Qq Ar 'skype,conemu'
.Ed
.
.
.Sh SEE ALSO
.Xr choco 1
.Pp
.Lk https://raw.githubusercontent.com/wiki/chocolatey/choco/images/gifs/choco_upgrade.gif "See it in action" .
.
.Sh HISTORY
Last revised for
.Nm choco
v0.10.11.
.
.Sh AUTHORS
\(co 2011-2017 RealDimensions Software, LLC
.br
\(co 2017-2019 Chocolatey Software, Inc
.Pp
Man page written by
.An Alhadis Aq Mt gardnerjohng\&@\&gmail.com .
