.Dd March 25, 2019
.Dt CHOCO-UNPACKSELF 1
.Os Windows
. 
.Sh NAME
.Nm choco-unpackself
.Nd have Chocolatey set itself up
.
.Sh SYNOPSIS
.Nm choco Cm unpackself
.
.Sh DESCRIPTION
This will unpack files needed by
.Nm choco .
It will overwrite existing files only if
.Fl -force
is specified.
.Pp
.Sy NOTE :
This command should only be used when installing Chocolatey,
not during normal operation.
.
.Sh SEE ALSO
.Xr choco 1
.
.Sh HISTORY
Last revised for
.Nm choco
v0.10.11.
.
.Sh AUTHORS
\(co 2011-2017 RealDimensions Software, LLC
.br
\(co 2017-2019 Chocolatey Software, Inc
.Pp
Man page written by
.An Alhadis Aq Mt gardnerjohng\&@\&gmail.com .
