.Dd March 25, 2019
.Dt CHOCO-CONFIG 1
.Os Windows
.Sh NAME
.Nm choco-config
.Nd retrieve and configure config file settings
.
.Sh SYNOPSIS
.Nm choco Cm config No [ list ] Ar options
.Nm choco Cm config No [ get Ns | Ns set Ns | Ns unset ] Ar options
.
.\" ============================================================================
.Sh OPTIONS
.Bl -tag -width 4n
.It Fl -name Ns [ No = Ns Ar VALUE ]
Name of the config setting.
Required with some actions.
Defaults to the empty string.
.
.It Fl -value Ns [ No = Ns Ar VALUE ]
Value of the config setting.
Required with some actions.
Defaults to the empty string.
.El
.Pp
In addition, the global options are available.
See
.Xr choco 1 .
.
.Sh SEE ALSO
.Xr choco 1
.Pp
.Lk https://raw.githubusercontent.com/wiki/chocolatey/choco/images/gifs/choco_config.gif "Config shown in action" .
.
.Sh HISTORY
The
.Cm config
command was added in
.Nm choco
v0.9.9.9.
The
.Cm unset
subcommand was added in
.Nm choco
v0.9.10.
.
.Pp
Man page last revised for
.Nm choco
v0.10.11.
.
.Sh AUTHORS
\(co 2011-2017 RealDimensions Software, LLC
.br
\(co 2017-2019 Chocolatey Software, Inc
.Pp
Man page written by
.An Alhadis Aq Mt gardnerjohng\&@\&gmail.com .
