.Dd March 25, 2019
.Dt CHOCO-PIN 1
.Os Windows
.
.Sh NAME
.Nm choco-pin
.Nd pin a package to suppress upgrades
.
.Sh SYNOPSIS
.Nm choco Cm pin Op list Ns No | add Ns No | remove
.Op options
.
.Sh DESCRIPTION
Pin a package to suppress upgrades.
.Pp
This is especially helpful when running
.Ql choco upgrade
for all packages, as it will automatically skip those packages.
Another alternative is
.Ql choco upgrade --except="pkg1,pk2" .
.
.Ss Options
.Bl -tag -width 4n
.It Fl n , Fl -name Ns No = Ns Ar VALUE
Name of the package.
Required with some actions.
Defaults to the empty string.
.
.It Fl -version Ns No = Ns Ar VALUE
Package version, used when multiple versions of a package are installed.
Defaults to the empty string.
.El
.
.Sh EXAMPLES
.Bd -literal
.Nm choco Cm pin
.Nm choco Cm pin list
.Nm choco Cm pin add Fl n Ns No = Ns Ar git
.Nm choco Cm pin add Fl n Ns No = Ns Ar git Fl -version Ar 1.2.3
.Nm choco Cm pin remove Fl -name Ar git
.Ed
.
.\" ============================================================================
.Sh HISTORY
Last revised for
.Nm choco
v0.10.11.
.
.Sh AUTHORS
\(co 2011-2017 RealDimensions Software, LLC
.br
\(co 2017-2019 Chocolatey Software, Inc
.Pp
Man page written by
.An Alhadis Aq Mt gardnerjohng\&@\&gmail.com .
