.Dd March 25, 2019
.Dt CHOCO-VERSION 1
.Os Windows
.
.Sh NAME
.Nm choco-version
.Nd deprecated command for listing install versions
.
.Sh DESCRIPTION
.Sy NOTE :
.Sy version
has been deprecated and will be removed in version 1.0.0.
If you are attempting to get local installed items, use
.Ql choco list -lo .
.Pp
If you want to know what has available upgrades, use
.Ql choco upgrade <pkg|all> -whatif
or
.Ql choco outdated .
.
.Ss Options
.Bl -tag -width 4n
.It Fl -lo , Fl -localonly
Only search against local machine items.
.
.It Fl -pre , Fl -prerelease
Whether to include prereleases.
Defaults to false.
.
.It Fl s , Fl -source Ns No = Ns Ar VALUE
The source to find the package(s) to install.
Special sources include:
.Ql ruby ,
.Ql webpi ,
.Ql cygwin ,
.Ql windowsfeatures ,
and
.Ql python .
Defaults to default feeds.
.El
.
.\" ----------------------------------------------------------------------------
.Sh HISTORY
Last revised for
.Nm choco
v0.10.11.
.
.Sh AUTHORS
\(co 2011-2017 RealDimensions Software, LLC
.br
\(co 2017-2019 Chocolatey Software, Inc
.Pp
Man page written by
.An Alhadis Aq Mt gardnerjohng\&@\&gmail.com .
