'\" t
.ad l
.nh
.
.TH TEXTMATE-CSS 5 "1 June 2017 19:00:38 GMT" "TextMate Manual" "CSS classes for TextMate scopes"
.SH INTRO
The table below lists the names of
.BR textmate (5)
grammar scopes recognised by GitHub's styling framework, Primer.
The scopes are mapped to CSS classes used to highlight rendered source-code.
.
.PP
Note this mapping is subject to change any time.
For the latest version of GitHub's scope-map, refer to the \fI*\.map\.json\fP file at
.UR https://\:github\.com/\:primer/\:github-syntax-light
the official Primer repository.
.UE
.
.TS
lb lbx
l lx .
Scope name	CSS class
_
brackethighlighter.angle	pl-ba
brackethighlighter.curly	pl-ba
brackethighlighter.quote	pl-ba
brackethighlighter.round	pl-ba
brackethighlighter.square	pl-ba
brackethighlighter.tag	pl-ba
brackethighlighter.unmatched	pl-bu
carriage-return	pl-c2
comment	pl-c
constant	pl-c1
constant.character.escape	pl-cce
constant.other.reference.link	pl-corl
entity	pl-e
entity.name	pl-en
entity.name.constant	pl-c1
entity.name.tag	pl-ent
invalid.broken	pl-bu
invalid.deprecated	pl-bu
invalid.illegal	pl-ii
invalid.unimplemented	pl-bu
keyword	pl-k
keyword.operator.symbole	pl-kos
keyword.other.mark	pl-kos
markup.bold	pl-mb
markup.changed	pl-mc
markup.deleted	pl-md
markup.heading	pl-mh
markup.ignored	pl-mi2
markup.inserted	pl-mi1
markup.italic	pl-mi
markup.list	pl-ml
markup.quote	pl-ent
markup.raw	pl-c1
markup.untracked	pl-mi2
message.error	pl-bu
meta.diff.header	pl-c1
meta.diff.header.from-file	pl-md
meta.diff.header.to-file	pl-mi1
meta.diff.range	pl-mdr
meta.module-reference	pl-c1
meta.output	pl-c1
meta.property-name	pl-c1
meta.separator	pl-ms
punctuation.definition.changed	pl-mc
punctuation.definition.comment	pl-c
punctuation.definition.deleted	pl-md
punctuation.definition.inserted	pl-mi1
punctuation.definition.string	pl-pds
punctuation.section.embedded	pl-pse
source	pl-s1
source.regexp	pl-pds
source.ruby.embedded	pl-sre
storage	pl-k
storage.modifier.import	pl-smi
storage.modifier.package	pl-smi
storage.type	pl-k
storage.type.java	pl-smi
string	pl-s
string.comment	pl-c
string.other.link	pl-corl
string.regexp	pl-sr
string.regexp.arbitrary-repitition	pl-sra
string.regexp.character-class	pl-pds
string.unquoted.import.ada	pl-kos
sublimelinter.gutter-mark	pl-sg
sublimelinter.mark.error	pl-bu
sublimelinter.mark.warning	pl-smw
support	pl-c1
support.constant	pl-c1
support.variable	pl-c1
variable	pl-v
variable.language	pl-c1
variable.other	pl-smi
variable.other.constant	pl-c1
variable.parameter.function	pl-smi
.TE
.
.SH SEE ALSO
.BR textmate (5)
.\" vim: ts=40
