.\" -*- nroff -*-
.de XR \" Cross-reference
.	ds X 3
.	ds Z
.	if !''\\$3' .ds X \\$3
.	if '.'\\$2' .ds Z \\$2
.	ie \\$2 .if !'.'\\$2' .It Xr \\fB\\$1\\fP \\*X \\*Z
.	el                       .Xr \\fB\\$1\\fP \\*X \\*Z
..
.de IX \" Item cross-reference
.	XR \\$1 1 \\$2
..
.de BL \" Begin list
.	Bl -tag -width 5n
..
.de EL \" End list
.	El
..
.de ( \" Bracketed coordinates
.	Ar ( \\$1 ,
.	Ar   \\$2 \\$3
..
.de Default: \" Default value
.	Sy Default:
.	CW \\$1
.	if !''\\$2' .No \\$2
..
.de CW \" Constant-width text
'	ie t \\f(CW\\$1\\fP\\$2
'	el   \\fI\\$1\\fP\\$2
..
.
.ds D April 5, 2017
.ds T 10:33:13 AM
.
.
.\" ============================================================================
.Dd \*D
.Dt CANVAS 3 "Web APIs"
.Os
.
.Sh NAME
.\" ----
.	Nm CanvasRenderingContext2D
.	Nd 2D rendering context for an HTML canvas element
.
.Sh DESCRIPTION
.\" -----------
The
.Nm
interface is used for drawing rectangles, text, images and other objects onto the canvas element.
It provides the 2D rendering context for the drawing surface of a
.XR canvas
element.
.
.Pp
To get an object of this interface, call
.XR getContext
on a
.XR canvas
element, supplying \fI2d\fP as the argument:
.
.Bd -literal
.\" JavaScript:
	// in your HTML this element appears as <canvas id="mycanvas"></canvas>
	let canvas = document.getElementById("myCanvas");
	let ctx = canvas.getContext("2d");
.Ed
.
.Pp
Once you have the 2D rendering context for a canvas, you can draw within it.
For example:
.
.Bd -literal
.\" JavaScript:
	ctx.fillStyle = "rgb(200,0,0)"; // Sets the colour to fill in the rectangle with
	ctx.fillRect(10, 10, 55, 50);   // Draws the rectangle at position 10, 10 with a width of 55 and a height of 50
.Ed
.
.\" ============================================================================
.Ss Drawing rectangles
There are three methods that immediately draw rectangles to the bitmap.
.BL
.\" ----------------------------------
.IX CanvasRenderingContext2D.clearRect
Set all pixels in the rectangle defined by starting point
.( x y )
and size
.( width height )
to transparent black, erasing any previously drawn content.
.\" ---------------------------------
.IX CanvasRenderingContext2D.fillRect
Draw a filled rectangle at
.( x y )
position whose size is determined by
.Ar width No and Ar height .
.\" -----------------------------------
.IX CanvasRenderingContext2D.strokeRect
Paint a rectangle which has a starting point at
.( x y )
and has a
.Ar w No width and an
.Ar h No height onto the canvas, using the current stroke style.
.EL
.
.\" ============================================================================
.Ss Drawing text
The following methods are provided for drawing text.
See also the
.XR TextMetrics
object for text properties.
.BL
.\" ---------------------------------
.IX CanvasRenderingContext2D.fillText
Draw (fill) a given text at the given
.( x y )
position.
.\" -----------------------------------
.IX CanvasRenderingContext2D.strokeText
Draw (stroke) a given text at the given
.( x y )
position.
.\" ------------------------------------
.IX CanvasRenderingContext2D.measureText
Return a
.XR TextMetrics
object.
.EL
.
.\" ============================================================================
.Ss Line styles
The following methods and properties control how lines are drawn.
.BL
.\" ----------------------------------
.IX CanvasRenderingContext2D.lineWidth
Width of lines.
.Default: 1.0
.\" --------------------------------
.IX CanvasRenderingContext2D.lineCap
Type of endings on the end of lines.
Possible values:
.CW butt ,
.CW round ,
.CW square .
.Default: butt
.\" ---------------------------------
.IX CanvasRenderingContext2D.lineJoin
Define the type of corners where two lines meet.
Possible values:
.CW round ,
.CW bevel ,
.CW miter .
.Default: miter
.\" -----------------------------------
.IX CanvasRenderingContext2D.miterLimit
Miter limit ratio.
.Default: 10
.\" ------------------------------------
.IX CanvasRenderingContext2D.getLineDash
Return the current line dash pattern array, containing an even number of non-negative numbers.
.\" ------------------------------------
.IX CanvasRenderingContext2D.setLineDash
Set the current line dash pattern.
.\" ---------------------------------------
.IX CanvasRenderingContext2D.lineDashOffset
Specify where to start a dash array on a line.
.EL
.
.\" ============================================================================
.Ss Text styles
The following properties control how text is laid out.
.BL
.\" -----------------------------
.IX CanvasRenderingContext2D.font
Font setting.
.Default: 10px\ sans-serif
.\" ----------------------------------
.IX CanvasRenderingContext2D.textAlign
Text alignment setting.
Possible values:
.CW start ,
.CW end ,
.CW left ,
.CW right ,
.CW center .
.Default: start
.\" -------------------------------------
.IX CanvasRenderingContext2D.textBaseline
Baseline alignment setting.
Possible values:
.CW top ,
.CW hanging ,
.CW middle ,
.CW alphabetic ,
.CW ideographic ,
.CW bottom .
.Default: alphabetic
.\" ----------------------------------
.IX CanvasRenderingContext2D.direction
Directionality.
Possible values:
.CW ltr ,
.CW rtl ,
.CW inherit .
.Default: inherit
.EL
.
.\" ============================================================================
.Ss Fill and stroke styles
Fill styling is used for colours and styles inside shapes, and stroke styling is used for the lines around shapes.
.BL
.\" ----------------------------------
.IX CanvasRenderingContext2D.fillStyle
Colour or style to use inside shapes.
.Default: #000 (black)
.\" ------------------------------------
.IX CanvasRenderingContext2D.strokeStyle
Colour or style to use for the lines around shapes.
.Default: #000 (black)
.EL
.
.\" ============================================================================
.Ss Gradients and patterns
.BL
.\" ---------------------------------------------
.IX CanvasRenderingContext2D.createLinearGradient
Create a linear gradient along the line given by the coordinates represented by the parameters.
.\" ---------------------------------------------
.IX CanvasRenderingContext2D.createRadialGradient
Create a radial gradient given by the coordinates of the two circles represented by the parameters.
.\" --------------------------------------
.IX CanvasRenderingContext2D.createPattern
Create a pattern using the specified image (a
.XR CanvasImageSource
instance).
It repeats the source in the directions specified by the repetition argument.
This method returns a
.XR CanvasPattern 0 3 .
.EL
.\" ============================================================================
.Ss Shadows
.BL
.\" -----------------------------------
.IX CanvasRenderingContext2D.shadowBlur
Specify the blurring effect.
.Default: 0
.\" ------------------------------------
.IX CanvasRenderingContext2D.shadowColor
Colour of the shadow.
.Default: rgba(0,\ 0,\ 0,\ 0) (fully-transparent\ black)
.\" --------------------------------------
.IX CanvasRenderingContext2D.shadowOffsetX
Horizontal distance the shadow will be offset.
.Default: 0
.\" --------------------------------------
.IX CanvasRenderingContext2D.shadowOffsetY
Vertical distance the shadow will be offset.
.Default: 0
.EL
.\" ============================================================================
.Ss Paths
The following methods can be used to manipulate paths of objects.
.BL
.\" ----------------------------------
.IX CanvasRenderingContext2D.beginPath
Start a new path by emptying the list of sub-paths.
Call this method when you want to create a new path.
.\" ----------------------------------
.IX CanvasRenderingContext2D.closePath
Force the point of the pen to move back to the start of the current sub-path.
It tries to draw a straight line from the current point to the start.
If the shape has already been closed or has only one point, this method does nothing.
.\" -------------------------------
.IX CanvasRenderingContext2D.moveTo
Move the starting point of a new sub-path to the coordinates
.( x y ).
.\" -------------------------------
.IX CanvasRenderingContext2D.lineTo
Connect the last point in the subpath to the coordinates
.( x y )
with a straight line.
.\" --------------------------------------
.IX CanvasRenderingContext2D.bezierCurveTo
Add a cubic B\['e]zier curve to the path.
It requires three points:
The first two points are control points, and the third one is the end point.
The starting point is the last point in the current path,
which can be changed using
.XR moveTo
before creating the B\['e]zier curve.
.\" -----------------------------------------
.IX CanvasRenderingContext2D.quadraticCurveTo
Add a quadratic B\['e]zier curve to the current path.
.\" ----------------------------
.IX CanvasRenderingContext2D.arc
Add an arc to the path which is centred at position
.( x y )
with radius
.Ar r No starting at
.Ar startAngle No and ending at
.Ar endAngle No going in the given direction by
.Ar anticlockwise No (defaulting to clockwise).
.\" ------------------------------
.IX CanvasRenderingContext2D.arcTo
Add an arc to the path with the given control points and radius, connected to the previous point by a straight line.
.\" --------------------------------
.IX CanvasRenderingContext2D.ellipse
Add an ellipse to the path which is centred at position
.( x y )
with the radii
.Ar radiusX No and
.Ar radiusY No starting at
.Ar startAngle No and ending at
.Ar endAngle No going in the given direction by
.Ar anticlockwise No (defaulting to clockwise).
.\" -----------------------------
.IX CanvasRenderingContext2D.rect
Create a path for a rectangle at position
.( x y )
with a size determined by
.Ar width No and Ar height .
.EL
.
.\" ============================================================================
.Ss Drawing paths
.BL
.\" -----------------------------
.IX CanvasRenderingContext2D.fill
Fill subpaths with the current fill style.
.\" -------------------------------
.IX CanvasRenderingContext2D.stroke
Stroke subpaths with the current stroke style.
.\" ------------------------------------------
.IX CanvasRenderingContext2D.drawFocusIfNeeded
If a given element is focused, this method draws a focus ring around the current path.
.\" -------------------------------------------
.IX CanvasRenderingContext2D.scrollPathIntoView
Scroll the current path (or a given path) into view.
.\" -----------------------------
.IX CanvasRenderingContext2D.clip
Create a clipping path from the current sub-paths.
Everything drawn after
.Sy clip
is called appears inside the clipping path only.
.\" --------------------------------------
.IX CanvasRenderingContext2D.isPointInPath
Report whether or not the specified point is contained in the current path.
.\" ----------------------------------------
.IX CanvasRenderingContext2D.isPointInStroke
Report whether or not the specified point is inside the area contained by the stroking of a path.
.EL
.
.\" ============================================================================
.Ss Transformations
Objects in the
.Nm
rendering context have a current transformation matrix and methods to manipulate it.
The transformation matrix is applied when creating the current default path, painting text, shapes and
.XR Path2D
objects.
The methods listed below remain for historical and compatibility reasons, as
.XR SVGMatrix
objects are used in most parts of the API nowadays and will be used in the future instead.
.
.BL
.IX CanvasRenderingContext2D.currentTransform
Current transformation matrix (an
.XR SVGMatrix
object).
.
.IX CanvasRenderingContext2D.rotate
Add a rotation to the transformation matrix.
The
.Ar angle
argument represents a clockwise rotation angle and is expressed in radians.
.
.IX CanvasRenderingContext2D.scale
Add a scaling transformation to the canvas units by
.Ar x No horizontally and by
.Ar y No vertically.
.
.IX CanvasRenderingContext2D.translate
Add a translation transformation by moving the canvas and its origin
.Ar x No horzontally and
.Ar y No vertically on the grid.
.
.IX CanvasRenderingContext2D.transform
Multiply the current transformation matrix with the matrix described by its arguments.
.
.IX CanvasRenderingContext2D.setTransform
Reset the current transform to the identity matrix, and invoke the
.XR transform
method with the same arguments.
.
.IX CanvasRenderingContext2D.resetTransform
Reset the current transform by the identity matrix.
.EL
.
.\" ============================================================================
.Ss Compositing
.BL
.\" ------------------------------------
.IX CanvasRenderingContext2D.globalAlpha
Alpha value applied to shapes and images before they are composited onto the canvas.
.Default: 1.0 (opaque)
.\" -------------------------------------------------
.IX CanvasRenderingContext2D.globalCompositeOperation
With
.XR globalAlpha
applied, this sets how shapes and images are drawn onto the existing bitmap.
.EL
.
.\" ============================================================================
.Ss Drawing images
.BL
.IX CanvasRenderingContext2D.drawImage
Draw the specified image.
This method is available in multiple formats, providing a great deal of flexibility in its use.
.EL
.
.\" ============================================================================
.Ss Pixel manipulation
See also
.XR ImageData
.BL
.\" ----------------------------------------
.IX CanvasRenderingContext2D.createImageData
Create a new, blank
.XR ImageData
object with the specified dimensions.
All of the pixels in the new object are transparent black.
.\" -------------------------------------
.IX CanvasRenderingContext2D.getImageData
Return an
.XR ImageData
object representing the underlying pixel data for the area of the canvas denoted by the rectangle, starting at
.( sx sy )
and has an
.Ar sw No width and
.Ar sh No height.
.\" -------------------------------------
.IX CanvasRenderingContext2D.putImageData
Paint data from the given
.XR ImageData
object onto the bitmap.
If a dirty rectangle is provided, only the pixels from that rectangle are painted.
.EL
.
.\" ============================================================================
.Ss Image smoothing
.BL
.\" ----------------------------------------------
.IX CanvasRenderingContext2D.imageSmoothingEnabled
Image smoothing mode.
If disabled, images will not be smoothed when scaled.
.EL
.
.\" ============================================================================
.Ss The canvas state
The
.Nm
rendering context contains a variety of drawing style states
(attributes for line styles, fill styles, shadow styles, text styles).
The following methods help you to work with that state:
.BL
.\" -----------------------------
.IX CanvasRenderingContext2D.save
Save the current drawing style state using a stack.
Changes can be reverted using
.XR restore .
.\" --------------------------------
.IX CanvasRenderingContext2D.restore
Restore the drawing style state to the last element on the \[lq]state stack\[rq] saved by
.XR save .
.\" -------------------------------
.IX CanvasRenderingContext2D.canvas
A read-only back-reference to the
.XR HTMLCanvasElement .
Might be null if not associated with a
.XR canvas
element.
.EL
.
.\" ============================================================================
.Ss Hit regions
.BL
.\" -------------------------------------
.IX CanvasRenderingContext2D.addHitRegion
Add a hit region to the canvas.
.\" ----------------------------------------
.IX CanvasRenderingContext2D.removeHitRegion
Remove the hit region with the specified
.Ar id
from the canvas.
.\" ----------------------------------------
.IX CanvasRenderingContext2D.clearHitRegions
Remove all hit regions from the canvas.
.EL
.
.\" ============================================================================
.Sh NON-STANDARD APIS
.Ss Blink and WebKit
Most of these APIs are deprecated and will be removed in the future.
.BL
.\" ------------------------------------
.IX CanvasRenderingContext2D.clearShadow
Remove all shadow settings like
.XR shadowColor
and
.XR shadowBlur .
.\" ------------------------------------------
.IX CanvasRenderingContext2D.drawImageFromRect
This is redundant with an equivalent overload of
.XR drawImage .
.\" ---------------------------------
.IX CanvasRenderingContext2D.setAlpha
Use
.XR globalAlpha
instead.
.\" ----------------------------------------------
.IX CanvasRenderingContext2D.setCompositeOperation
Use
.XR globalCompositeOperation
instead.
.\" -------------------------------------
.IX CanvasRenderingContext2D.setLineWidth
Use
.XR lineWidth
instead.
.\" ------------------------------------
.IX CanvasRenderingContext2D.setLineJoin
Use
.XR lineJoin
instead.
.\" -----------------------------------
.IX CanvasRenderingContext2D.setLineCap
Use
.XR lineCap
instead.
.\" --------------------------------------
.IX CanvasRenderingContext2D.setMiterLimit
Use
.XR miterLimit instead.
.\" ---------------------------------------
.IX CanvasRenderingContext2D.setStrokeColor
Use
.XR strokeStyle
instead.
.\" -------------------------------------
.IX CanvasRenderingContext2D.setFillColor
Use
.XR fillStyle
instead.
.\" ----------------------------------
.IX CanvasRenderingContext2D.setShadow
Use
.XR shadowColor
and
.XR shadowBlur
instead.
.\" ---------------------------------------
.IX CanvasRenderingContext2D.webkitLineDash
Use
.XR getLineDash
and
.XR setLineDash
instead.
.\" ---------------------------------------------
.IX CanvasRenderingContext2D.webkitLineDashOffset
Use
.XR lineDashOffset
instead.
.\" ----------------------------------------------------
.IX CanvasRenderingContext2D.webkitImageSmoothingEnabled
Use
.XR imageSmoothingEnabled
instead.
.EL
.
.\" ============================================================================
.Ss Blink only
.BL
.IX CanvasRenderingContext2D.isContextLost
Inspired by the same
.XR WebGLRenderingContext
method.
Returns
.Ar true  No if the canvas context has been lost, and
.Ar false No if not.
.EL
.
.\" ============================================================================
.Ss WebKit only
.BL
.IX CanvasRenderingContext2D.webkitBackingStorePixelRatio
The backing store size in relation to the canvas element.
.\" ---------------------------------------------
.IX CanvasRenderingContext2D.webkitGetImageDataHD
Intended for HD backing stores, but removed from canvas specifications.
.\" ---------------------------------------------
.IX CanvasRenderingContext2D.webkitPutImageDataHD
Intended for HD backing stores, but removed from canvas specifications.
.EL
.
.\" ============================================================================
.Ss Gecko only
.BL
.IX CanvasRenderingContext2D.filter
CSS and SVG filters as Canvas APIs.
Likely to be standardised in a new version of the specification.
.EL
.
.\" ============================================================================
.Ss Prefixed APIs
.BL
.\" --------------------------------------------
.IX CanvasRenderingContext2D.mozCurrentTransform
Set or get the current transformation matrix.
See
.XR currentTransform .
.\" ---------------------------------------------------
.IX CanvasRenderingContext2D.mozCurrentTransformInverse
Set or get the current inversed transformation matrix.
.\" -------------------------------------------------
.IX CanvasRenderingContext2D.mozImageSmoothingEnabled
See
.XR imageSmoothingEnabled .
.\" -------------------------------------
.IX CanvasRenderingContext2D.mozTextStyle
Introduced in Gecko 1.9.
Deprecated in favour of the
.XR font
property.
.\" ------------------------------------
.IX CanvasRenderingContext2D.mozDrawText
Introduced in Gecko 1.9, and removed since Gecko 7.0.
Use
.XR strokeText
or
.XR fillText
instead.
.\" ---------------------------------------
.IX CanvasRenderingContext2D.mozMeasureText
Introduced in Gecko 1.9.
Unimplemented since Gecko 7.0.
Use
.XR measureText
instead.
.\" ------------------------------------
.IX CanvasRenderingContext2D.mozPathText
Introduced in Gecko 1.9.
Removed since Gecko 7.0.
.\" -----------------------------------------
.IX CanvasRenderingContext2D.mozTextAlongPath
Introduced in Gecko 1.9.
Removed since Gecko 7.0.
.EL
.
.\" ============================================================================
.Ss Internal APIs (chrome-context only)
.BL
.\" -----------------------------------
.IX CanvasRenderingContext2D.drawWindow
Render a region of a window's viewport onto the canvas, ignoring viewport clipping and scrolling.
.\" -------------------------------
.IX CanvasRenderingContext2D.demote
Cause a context currently using a hardware-accelerated backend to fallback to a software one.
All state should be preserved.
.EL
.
.\" ============================================================================
.Ss Internet Explorer
.BL
.IX CanvasRenderingContext2D.msFillRule
The fill rule to use.
This must be one of
.Ar evenodd No or
.Ar nonzero .
.Default: nonzero
.EL
.
.\" ============================================================================
.Sh SEE ALSO
.XR HTMLCanvasElement
.Pp
.Lk https://html.spec.whatwg.org/multipage/scripting.html#2dcontext:canvasrenderingcontext2d "WHATWG HTML Living Standard"
.D1 The definition of Sy CanvasRenderingContext2D No in that specification.
.
.
.Sh BROWSER COMPATIBILITY
.\" ---------------------
.Ss Desktop
.
.TS
tab(|) allbox;
lb lb lb lb lb lb lb
l  l  l  l  l  l  l .
Feature|Chrome|Edge|Firefox|Internet Explorer|Opera|Safari
Basic support|1|Yes|1.5|9|9|2
.TE
.
.Ss Mobile
.
.TS
tab(|) allbox;
lb lb lb lb lb lb lb lb
l  l  l  l  l  l  l  l .
Feature|Android|Chrome|Edge|Firefox|IE|Opera|Safari
Basic support|?|?|Yes|?|?|?|?
.TE
.sp
.
.Sh GECKO-SPECIFIC NOTES
.\" --------------------
Starting with Gecko 5.0 (Firefox 5.0 / Thunderbird 5.0 / SeaMonkey 2.2),
specifying invalid values are now silently ignored for the following methods and properties:
.
.Bd -ragged -offset 4n
.	ll 100n
.	Sy arc , clearRect , fillRect , lineTo , moveTo , quadraticCurveTo , rect , rotate , \
scale , shadowBlur , shadowOffsetX , shadowOffsetY , strokeRect , transform , translate .
.Ed
.
.Sh AUTHORS
.\" -------
.Sy 2is10 , adion , Brettz9 , cactus1 , chapko , chrisdavidmills , cirocosta , cpmsmith , \
deepakyadav , Dimanjy , drezabek94 , erikadoyle , fscholz , GijsKruitbosch , JaredWein , \
Jeremie , Jonathan_Watt , kathyw , kscarfone , Mahdi , Manuel_Strehl , Ms2ger , nmve , \
Noitidart , rudolfo , rvighne , shanebdavis , Sheppy , strawn_04 , tehsis , teoli , \
thaddee.tyl\(atgm\&ail\&.com , therold , trevorh , zakerinasab .
.Pp
Last updated by \fBzakerinasab\fP on \*D, \*T.
