(global-unset-key [(control z)])
(global-unset-key [(control x)(control z)])
(global-unset-key [(control h)(control c)])

(global-set-key (kbd "C-h C-f") 'describe-function)
(global-set-key (kbd "C-h C-c") 'describe-key-briefly)
(global-set-key (kbd "<f7>") 'ispell-buffer)
(global-set-key (kbd "C-<up>") `move-text-up)
(global-set-key (kbd "C-<down>") `move-text-down)
(global-set-key (kbd "C-]") 'next-buffer)
(global-set-key (kbd "C-n") 'find-file)
(global-set-key (kbd "C-o") 'find-file-at-point)
(global-set-key (kbd "C-w")  (lambda () (interactive) (kill-buffer)))
(global-set-key (kbd "C-u")  (lambda () (interactive) (kill-line 0)))
(global-set-key (kbd "<f1>") (lambda () (interactive) (manual-entry (current-word))))
